/** @format */

import LocalizedStrings from "react-native-localization";

export default new LocalizedStrings({
  en: {
    Exit: "Exit",
    ExitConfirm: "Are you sure you want to exit this app",
    YES: "YES",
    OK: "OK",
    ViewMyOrders: "View My Oders",
    CANCEL: "CANCEL",
    Confirm: "Confirm",

    // Scene's Titles
    Home: "Home",
    Intro: "Intro",
    Product: "Product",
    Cart: "Cart",
    WishList: "WishList",
    InputPhone: "Please input your phone",

    // Home
    products: "products",

    // TopBar
    ShowFilter: "Sub Categories",
    HideFilter: "Hide",
    Sort: "Sort",
    textFilter: "Recent",

    // Category
    ThereIsNoMore: "There is no more product to show",

    // Product
    AddedtoCart: "Added item to Cart",
    AddtoCart: "Add to Cart",
    AddtoWishlist: "Add to Wishlist",
    ProductVariations: "Variations",
    NoVariation: "This product don't have any variation",
    AdditionalInformation: "Description",
    NoProductDescription: "No Product Description",
    ProductReviews: "Reviews",
    NoReview: "This product don't have any reviews ...yet",
    BUYNOW: "BUY NOW",
    ProductLimitWaring: "You can't add more than 10 product",
    EmptyProductAttribute: "This product don't have any attributes",
    ProductFeatures: "Features",
    ErrorMessageRequest: "Can't get data from server",
    NoConnection: "No internet connection",
    ProductRelated: "You May Also Like",

    // Cart
    NoCartItem: "There is no product in cart",
    Total: "Total",
    EmptyCheckout: "Sorry, you can't check out an empty cart",
    RemoveCartItemConfirm: "Remove this product from cart?",
    MyCart: "Cart",
    Order: "Order",
    ShoppingCart: "Shopping Cart",
    ShoppingCartIsEmpty: "Your Cart is Empty",
    Delivery: "Delivery",
    AddProductToCart: "Add a product to the shopping cart",
    TotalPrice: "Total Price:",
    YourDeliveryInfo: "Your delivery info:",
    ShopNow: "Shop Now",
    YourChoice: "Your wishlist:",
    YourSale: "Your Sale:",
    SubtotalPrice: "Subtotal Price:",
    BuyNow: "Buy Now",
    Items: "items",
    Item: "item",
    ThankYou: "Thank you",
    FinishOrderCOD: "You can use to number of order to track shipping status",
    FinishOrder:
      "Thank you so much for your purchased, to check your delivery status please go to My Orders",
    NextStep: "Next Step",
    ConfirmOrder: "Confirm Order",
    RequireEnterAllFileds: "Please enter all fields",
    Error: "Error",
    InvalidEmail: "Invalid email address",
    Finish: "Finish",

    // Wishlist
    NoWishListItem: "There is no item in wishlist",
    MoveAllToCart: "Add all to cart",
    EmptyWishList: "Empty wishlist",
    EmptyAddToCart: "Sorry, the wishlist is empty",
    RemoveWishListItemConfirm: "Remove this product from wishlist?",
    CleanAll: "Clean All",

    // Sidemenu
    SignIn: "Log In",
    SignOut: "Log Out",
    GuestAccount: "Guest Account",
    CantReactEmailError:
      "We can't reach your email address, please try other login method",
    NoEmailError: "Your account don't have valid email address",
    EmailIsNotVerifiedError:
      "Your email address is not verified, we can' trust you",
    Shop: "Shop",
    News: "News",
    Contact: "Contact us",
    Setting: "Setting",
    Login: "Login",
    Logout: "Logout",
    Category: "Category",

    // Checkout
    Checkout: "Checkout",
    ProceedPayment: "Proceed Payment",
    Purchase: "Purchase",
    CashOnDelivery: "Cash on Delivery",
    Paypal: "Paypal",
    Stripe: "Stripe",
    CreditCard: "Credit Card",
    PaymentMethod: "Payment Method - Not select",
    PaymentMethodError: "Please select your payment method",
    PayWithCoD: "Your purchase will be pay when goods were delivered",
    PayWithPayPal: "Your purchase will be pay with PayPal",
    PayWithStripe: "Your purchase will be pay with Stripe",
    ApplyCoupon: "Apply",
    CouponPlaceholder: "COUPON CODE",
    APPLY: "APPLY",
    Back: "Back",
    CardNamePlaceholder: "Name written on card",
    BackToHome: "Back to Home",
    OrderCompleted: "Your order was completed",
    OrderCanceled: "Your order was canceled",
    OrderFailed: "Something went wrong...",
    OrderCompletedDesc: "Your order id is ",
    OrderCanceledDesc:
      "You have canceled the order. The transaction has not been completed",
    OrderFailedDesc:
      "We have encountered an error while processing your order. The transaction has not been completed. Please try again",
    OrderTip:
      'Tip: You could track your order status in "My Orders" section from side menu',
    Payment: "Payment",
    Complete: "Complete",
    EnterYourFirstName: "Enter your First Name",
    EnterYourLastName: "Enter your Last Name",
    EnterYourEmail: "Enter your email",
    EnterYourPhone: "Enter your phone",
    EnterYourAddress: "Enter your address",
    CreateOrderError: "Cannot create new order. Please try again later",
    AccountNumner: "Account number",
    CardHolderName: "Cardholder Name",
    ExpirationDate: "Expiration Date",
    SecurityCode: "CVV",

    // myorder
    OrderId: "Order ID",
    MyOrder: "My Orders",
    NoOrder: "You don't have any orders",
    OrderDate: "Order Date: ",
    OrderStatus: "Status: ",
    OrderPayment: "Payment method: ",
    OrderTotal: "Total: ",
    OrderDetails: "Show detail",
    ShippingAddress: "Shipping Address:",
    Refund: "Refund",

    PostDetails: "Post Details",
    FeatureArticles: "Feature articles",
    MostViews: "Most views",
    EditorChoice: "Editor choice",

    // settings
    Settings: "Settings",
    BASICSETTINGS: "BASIC SETTINGS",
    Language: "Language",
    INFO: "INFO",
    About: "About us",
    changeRTL: "Switch RTL",

    // language
    AvailableLanguages: "Available Languages",
    SwitchLanguage: "Switch Language",
    SwitchLanguageConfirm: "Switch language require an app reload, continue?",
    SwitchRtlConfirm: "Switch RTL require an app reload, continue?",

    // about us
    AppName: "MSTORE",
    AppDescription: "React Native template for mCommerce",
    AppContact: " Contact us at: mstore.io",
    AppEmail: " Email: support@mstore.io",
    AppCopyRights: "© MSTORE 2016",

    // contact us
    contactus: "Contact us",

    // form
    NotSelected: "Not selected",
    EmptyError: "This field is empty",
    DeliveryInfo: "Delivery Info",
    FirstName: "First Name",
    LastName: "Last Name",
    Address: "Address",
    City: "Town/City",
    State: "State",
    NotSelectedError: "Please choose one",
    Postcode: "Postcode",
    Country: "Country",
    Email: "Email",
    Phone: "Phone Number",
    Note: "Note",

    // search
    Search: "Search",
    SearchPlaceHolder: "Search product by name",
    NoResultError: "Your search keyword did not match any products.",
    Details: "Details",

    // filter panel
    Categories: "Categories",

    // sign up
    profileDetail: "Profile Details",
    firstName: "First name",
    lastName: "Last name",
    accountDetails: "Account Details",
    username: "Username",
    email: "Email",
    generatePass: "Use generate password",
    password: "Password",
    signup: "Sign Up",

    // filter panel
    Loading: "LOADING...",
    welcomeBack: "Welcome back! ",
    seeAll: "Show All",

    // Layout
    cardView: "Card ",
    simpleView: "List View",
    twoColumnView: "Two Column ",
    threeColumnView: "Three Column ",
    listView: "List View",
    default: "Default",
    advanceView: "Advance ",
    horizontal: "Horizontal ",

    couponCodeIsExpired: "This coupon code is expired",
    invalidCouponCode: "This coupon code is invalid",
    remove: "Remove",
    reload: "Reload",
    applyCouponSuccess: "Congratulations! Coupon code applied successfully ",
    applyCouponFailMin: `This minimum spend for this coupon is `,
    applyCouponFailMax: `This maximum spend for this coupon is `,

    OutOfStock: "OUT OF STOCK",
    ShippingType: "Shipping method",

    // Place holder
    TypeFirstName: "Type your first name",
    TypeLastName: "Type your last name",
    TypeAddress: "Type address",
    TypeCity: "Type your town or city",
    TypeState: "Type your state",
    TypeNotSelectedError: "Please choose one",
    TypePostcode: "Type postcode",
    TypeEmail: "Type email (Ex. acb@gmail.com), ",
    TypePhone: "Type your phone number",
    TypeNote: "Note",
    TypeCountry: "Select country",
    SelectPayment: "Select Payment method",
    close: "CLOSE",
    noConnection: "NO INTERNET ACCESS",

    // user profile screen
    AccountInformations: "Account Informations",
    PushNotification: "Push notification",
    DarkTheme: "Dark Theme",
    Privacy: "Privacy policies",
    SelectCurrency: "Select currency",
    Name: "Name",
    Currency: "Currency",
    Languages: "Languages",

    GetDataError: "Can't get data from server",
    UserOrEmail: "Username or email",
    Or: "Or",
    FacebookLogin: "Facebook Login",
    DontHaveAccount: "Don't have an account?",

    // Horizontal
    featureProducts: "Feature Products",
    bagsCollections: "Bags Collections",
    womanBestSeller: "Woman Best Seller",
    manCollections: "Man Collections",

    // Modal
    Select: "Select",
    Cancel: "Cancel",
    Guest: "Guest",

    LanguageName: "English",

    // review
    vendorTitle: "Vendor",
    comment: "Leave a review",
    yourcomment: "Your comment",
    placeComment:
      "Tell something about your experience or leave a tip for others",
    writeReview: "Review",
    thanksForReview:
      "Thanks for the review, your content will be verify by the admin and will be published later",
    errInputComment: "Please input your content to submit",
    errRatingComment: "Please rating to submit",
    send: "Send",

    termCondition: "Term & Condition",
    Subtotal: "Subtotal",
    Discount: "Discount",
    Shipping: "Shipping",
    Taxes: "Taxes",
    Recents: "Recents",
    Filters: "Filters",
    Princing: "Pricing",
    Filter: "Filter",
    ClearFilter: "Clear Filter",
    ProductCatalog: "Product Catalog",
    ProductTags: "Product Tags",
    AddToAddress: "Add to Address",
    SMSLogin: "SMS Login",
    OrderNotes: "Order Notes",

    CanNotLogin: "Can not login, something was wrong!",
    PleaseCompleteForm: "Please complete the form!",
    ServerNotResponse: "Server doesn't response correctly",
    CanNotRegister: "Can't register user, please try again.",

    UserProfile: "User Profile",
    LoadMore: "Load More"
  },
  ar: {
    Exit: "خروج",
    ExitConfirm: "هل تود الخروج من التطبيق",
    YES: "نعم",
    OK: "نعم",
    ViewMyOrders: "أستعرض طلبي",
    CANCEL: "إلغاء",
    Confirm: "تأكيد",

    // Scene's Titles
    Home: "الرئيسة",
    Intro: "مقدمة",
    Product: "منتج",
    Cart: "عربة التسوق",
    WishList: "الرغبات",

    // Home
    products: "منتجات",

    // TopBar
    ShowFilter: "الفئات الفرعية",
    HideFilter: "إخفاء",
    Sort: "فرز",
    textFilter: "الأخيرة",

    // Category
    ThereIsNoMore: "لا يوجد منتجات لإظهارها",

    // Product
    AddedtoCart: "إضافة عنصر إلى السلة",
    AddtoCart: "أضف إلى السلة",
    AddtoWishlist: "أضف إلى قائمة الرغبات",
    ProductVariations: "الاختلافات",
    NoVariation: "هذا المنتج ليس لديهم أي اختلاف",
    AdditionalInformation: "معلومات",
    NoProductDescription: "لا يوجد وصف",
    ProductReviews: "التعليقات",
    NoReview: "لا توجد مراجعات لهذا المنتج",
    BUYNOW: "اشتر الآن",
    ProductLimitWaring: "لا يمكن اضافة اكثر من هذا العدد",
    EmptyProductAttribute: "لم يتم اضافة اي صفات لهذا المنتج",
    ProductFeatures: "المميزات",
    ErrorMessageRequest: "لا يمكن الحصول على البيانات من الخادم",
    NoConnection: "انت غير متصل بالإنترنت",
    ProductRelated: "ربما يعجبك أيضا",
    // Cart
    NoCartItem: "لا يوجد منتجات في العربة",
    Total: "مجموع",
    EmptyCheckout: "عذراً، لا يمكن الاستمرار مع عربة فارغة",
    RemoveCartItemConfirm: "إزالة هذا المنتج من سلة المشتريات؟",
    MyCart: "عربة التسوق",
    Order: "طلب",
    ShoppingCart: "عربة التسوق",
    ShoppingCartIsEmpty: "عربة التسوق فارغة",
    Delivery: "التوصيل",
    AddProductToCart: "إضافة منتج إلى عربة التسوق",
    TotalPrice: "السعر الكلي:",
    YourDeliveryInfo: "معلومات الإستلام:",
    ShopNow: "تسوق الآن",
    YourChoice: "عربتك:",
    YourSale: "مبيعاتك:",
    SubtotalPrice: "السعر الإجمالي:",
    BuyNow: "اشتر الآن",
    Items: "العناصر",
    Item: "عنصر",
    ThankYou: "شكراً لك",
    FinishOrderCOD: "يمكنك استخدام هذا الرقم لتتبع شحنتك",
    FinishOrder:
      "شكراً لإتمام عملية الشراء, للتحقق من حالة الطلب الرجاء مراجعة طلباتي",
    NextStep: "الخطوة التالية",
    ConfirmOrder: "أكد الطلب",
    RequireEnterAllFileds: "الرجاء إدخال جميع الحقول",
    Error: "خطأ",
    InvalidEmail: "البريد الإلكتروني غير صحيح",
    Finish: "إنهاء",

    // Wishlist
    NoWishListItem: "لا يوجد منتجات في قائمة الرغبات",
    MoveAllToCart: "اضف الكل للسلة",
    EmptyWishList: "القائمة فارغة",
    EmptyAddToCart: "عذرا، قائمة الرغبات فارغة",
    RemoveWishListItemConfirm: "إزالة هذا المنتج من قائمة الرغبات؟",
    CleanAll: "ازالة الكل",

    // Sidemenu
    SignIn: "تسجيل الدخول",
    SignOut: "خروج",
    GuestAccount: "زائر",
    CantReactEmailError: "هذا البريد غير موجود، جرب طريقة تسجيل دخول أخرى",
    NoEmailError: "البريد الإلكتروني المضاف غير صحيح",
    EmailIsNotVerifiedError:
      "لم يتم التحقق من بريدك الإلكتروني، لن يتم تفعيل حسابك",
    Shop: "المتجر",
    News: "الأخبار",
    Contact: "اتصل بنا",
    Setting: "الإعدادات",
    Login: "تسجيل الدخول",
    Logout: "تسجيل خروج",
    Category: "التصنيف",

    // Checkout
    Checkout: "الدفع",
    ProceedPayment: "متابعة الدفع",
    Purchase: "شراء",
    CashOnDelivery: "الدفع عن الاستلام",
    Paypal: "باي بال",
    Stripe: "شريط",
    CreditCard: "بطاقة ائتمان",
    PaymentMethod: "طريقة الدفع - غير محدد",
    PaymentMethodError: "يرجى تحديد طريقة الدفع",
    PayWithCoD: "يرجى تحديد طريقة الدفع",
    PayWithPayPal: "الدفع بواسطة Paypal",
    PayWithStripe: "سيتم دفع الشراء مع Stripe",
    ApplyCoupon: "اضف الكوبون",
    CouponPlaceholder: "رمز الكوبون",
    APPLY: "ارسل",
    Back: "العودة",
    CardNamePlaceholder: "الاسم مكتوب على البطاقة",
    BackToHome: "العودة لرئيسة",
    OrderCompleted: "تم الانتهاء من طلبك",
    OrderCanceled: "تم إلغاء طلبك",
    OrderFailed: "تم إلغاء طلبك",
    OrderCompletedDesc: "أجل معرف الخاص بك هو ",
    OrderCanceledDesc: "تم الغاء الطلب بناء على رغبتك",
    OrderFailedDesc: "حصل خطأ ولم تكتمل عملية الشراء",
    OrderTip:
      'إضاءة: يمكنك تتبع حالة الطلب في قسم "طلباتي" من القائمة الجانبية',
    Payment: "دفع",
    Complete: "دفع...",
    EnterYourFirstName: "أدخل اسمك الأول",
    EnterYourLastName: "أدخل اسم العائلة",
    EnterYourEmail: "أدخل بريدك الإلكتروني",
    EnterYourPhone: "أدخل هاتفك",
    EnterYourAddress: "أدخل عنوانك",
    CreateOrderError: "أدخل عنوانك...",
    AccountNumner: "رقم حساب",
    CardHolderName: "إسم صاحب البطاقة",
    ExpirationDate: "تاريخ إنتهاء الصلاحية",
    SecurityCode: "CVV",

    // myorder
    OrderId: "رقم التعريف الخاص بالطلب",
    MyOrder: "طلبي",
    NoOrder: "لا يوجد طلبات",
    OrderDate: "تاريخ الطلب: ",
    OrderStatus: "الحالة: ",
    OrderPayment: "طريقة الدفع او السداد: ",
    OrderTotal: "مجموع: ",
    OrderDetails: "أظهر تفاصيل",
    ShippingAddress: "عنوان الشحن:",
    Refund: "إعادة مال",

    PostDetails: "قراءة المزيد",
    FeatureArticles: "مقالات",
    MostViews: "الأكثر مشاهدة",
    EditorChoice: "من اختياراتنا",

    // settings
    Settings: "الإعدادات",
    BASICSETTINGS: "الإعدادات الأساسية",
    Language: "اللغو",
    INFO: "معلومات",
    About: "معلومات عنا",
    changeRTL: "تغيير الإتجاه",

    // language
    AvailableLanguages: "اللغات المتوفرة",
    SwitchLanguage: "تبديل اللغة",
    SwitchLanguageConfirm:
      "لتبديل اللغة سوف نقوم باعادة تحميل التطبيق، هل تود المتابعة؟",
    SwitchRtlConfirm:
      "لتغيير اتجاه التطبيق سوف نقوم بإعادة تحميل التطبيق, هل تود المتابعة؟",

    // about us
    AppName: "MSTORE",
    AppDescription: "رد القالب الأصلي ل كومومرس",
    AppContact: " الاتصال بنا على: mstore.io",
    AppEmail: " البريد الإلكتروني: support@mstore.io",
    AppCopyRights: "© MSTORE 2016",

    // contact us
    contactus: "اتصل بنا",

    // form
    NotSelected: "فضلاً اختر",
    EmptyError: "عبئ هذ الحقل",
    DeliveryInfo: "معلومات التسليم",
    FirstName: "الاسم الاول",
    LastName: "الكنية",
    Address: "عنوان",
    City: "المدينة / المدينة",
    State: "حالة",
    NotSelectedError: "إختر واحد من فضلك",
    Postcode: "الرمز البريدي",
    Country: "بلد",
    Email: "البريد الإلكتروني",
    Phone: "رقم الهاتف",
    Note: "ملاحظة",

    // search
    Search: "البحث",
    SearchPlaceHolder: "البحث عن المنتج بالاسم",
    NoResultError: "نأسف، لا توجد نتائج بحث للكلمات المستخدمة",
    Details: "التفاصيل",

    // filter panel
    Categories: "الاقسام",

    // sign up
    profileDetail: "تفاصيل الملف الشخصي",
    firstName: "الاسم الاول",
    lastName: "الكنية",
    accountDetails: "تفاصيل الحساب",
    username: "اسم المستخدم",
    email: "البريد الإلكتروني",
    generatePass: "أنشأ لي كلمة مرور",
    password: "كلمه السر",
    signup: "سجل",

    // filter panel
    Loading: "جار التحميل...",
    welcomeBack: "مرحبا بعودتك! ",
    seeAll: "استعراض الكل",

    // Layout
    cardView: "بطاقة",
    simpleView: "قائمة مبسطة",
    twoColumnView: "عمودين",
    threeColumnView: "ثلاثة أعمدة",
    listView: "قائمة عمودية",
    default: "افتراضي",
    advanceView: "اسلوب متقدم",
    horizontal: "أفقي ",

    couponCodeIsExpired: "لم يعد هذا الكوبون صالح",
    invalidCouponCode: "هذا الكوبون غير صحيح",
    remove: "إزالة",
    applyCouponSuccess: "تهانينا! تم تطبيق الكوبون بنجاح",
    reload: "إعادة تحميل",

    OutOfStock: "نفذت الكمية",
    ShippingType: "طريقة الشحن",

    // Place holder
    TypeFirstName: "اكتب اسمك الأول",
    TypeLastName: "اكتب اسمك الأخير",
    TypeAddress: "اكتب العنوان",
    TypeCity: "اكتب مدينتك أو مدينتك",
    TypeState: "اكتب الولاية أو المدينة",
    TypeNotSelectedError: "إختر واحد من فضلك",
    TypePostcode: "اكتب الرمز البريدي",
    TypeEmail: "اكتب بريد الكتروني صحيح مثل email@email.com: ",
    TypePhone: "اكتب رقم هاتفك",
    TypeNote: "ملاحظة",
    TypeCountry: "حدد دولتك",
    SelectPayment: "اختار طريقة الدفع",
    close: "أغلق",
    noConnection: "لا يوجد اتصال بالإنترنت",

    // user profile screen
    AccountInformations: "معلومات الحساب",
    PushNotification: "التنبيهات",
    DarkTheme: "موضوع الظلام",
    Privacy: "سياسة الخصوصية",
    SelectCurrency: "اختر العملة",
    Name: "اسم",
    Currency: "عملة",
    Languages: "اللغات",

    GetDataError: "لا يمكن الاتصال بالخادم",
    UserOrEmail: "اسم المستخدم أو البريد الالكتروني",
    Or: "أو",
    FacebookLogin: "تسجيل الدخول بواسطة الفيس بوك",
    DontHaveAccount: "لا تمتلك حساب؟",

    // Horizontal
    featureProducts: "منتجات مميزة",
    bagsCollections: "تشكيلة الحقائب",
    womanBestSeller: "افضل مبيعات منتجات المرأة",
    manCollections: "تشكيلة الرجل",

    // Modal
    Select: "تحديد",
    Cancel: "إلغاء",
    Guest: "زائر",

    LanguageName: "Arabic",

    // review
    vendorTitle: "بائع",
    comment: "ترك التعليق",
    yourcomment: "تعليقك",
    placeComment: "أخبر شيئًا عن تجربتك أو اترك نصيحة للآخرين",
    writeReview: "أكتب مراجعة",
    thanksForReview:
      "شكرًا على المراجعة ، سيتم التحقق من المحتوى الخاص بك بواسطة المشرف وسيتم نشره لاحقًا",
    errInputComment: "يرجى إدخال المحتوى الخاص بك لتقديمه",
    errRatingComment: "يرجى تصنيف لتقديم",
    send: "إرسال",

    termCondition: "الأحكام والشروط",
    Subtotal: "حاصل الجمع",
    Discount: "خصم",
    Shipping: "الشحن",
    Taxes: "الضرائب",
    Recents: "الأخيرة",
    Filters: "مرشحات",
    Princing: "التسعير",
    Filter: "منقي",
    ClearFilter: "مرشح واضح",
    ProductCatalog: "بيان المنتج",
    ProductTags: "علامات المنتج",
    AddToAddress: "أضف إلى العنوان",
    SMSLogin: "تسجيل الدخول عبر الرسائل القصيرة",
    OrderNotes: "ترتيب ملاحظات",

    CanNotLogin: "لا يمكن تسجيل الدخول ، كان هناك خطأ!",
    PleaseCompleteForm: "يرجى ملء النموذج!",
    ServerNotResponse: "الخادم لا يستجيب بشكل صحيح",
    CanNotRegister: "لا يمكن تسجيل المستخدم ، يرجى المحاولة مرة أخرى.",

    UserProfile: "ملف تعريفي للمستخدم",
    LoadMore: "تحميل المزيد"
  },
  cn: {
    Exit: "退出",
    ExitConfirm: "你确定要退出这个应用程序",
    YES: "是的",
    OK: "OK",
    ViewMyOrders: "查看我的订单",
    CANCEL: "取消",
    Confirm: "确认",
    ////场景的标题
    Home: "家",
    Intro: "介绍",
    Product: "产品",
    Cart: "购物车",
    WishList: "愿望列表",
    InputPhone: "请填写您的电话号码",
    // 家
    products: "产品",
    // TopBar
    ShowFilter: "子类别",
    HideFilter: "隐藏",
    Sort: "排序",
    textFilter: "最近",
    //类别
    ThereIsNoMore: "没有更多的产品展示",
    //产品
    addtocart: "添加项目到购物车",
    AddtoCart: "添加到购物车",
    AddtoWishlist: "添加到愿望列表",
    ProductVariations: "变化",
    NoVariation: "本产品无变型",
    AdditionalInformation: "描述",
    NoProductDescription: "无产品描述",
    ProductReviews: "评论",
    NoReview: "该产品目前还没有任何评论……",
    BUYNOW: "现在购买",
    ProductLimitWaring: "你不能添加超过10个产品",
    EmptyProductAttribute: "此产品没有任何属性",
    ProductFeatures: "功能",
    ErrorMessageRequest: "不能从服务器获取数据",
    NoConnection: "没有网络连接",
    ProductRelated: "你可能也喜欢",
    //购物车
    NoCartItem: "购物车里没有产品",
    Total: "总",
    EmptyCheckout: "对不起,您不能在空车里结账",
    RemoveCartItemConfirm: "从购物车中移除此产品 ?",
    MyCart: "购物车",
    Order: "秩序",
    ShoppingCart: "购物车",
    ShoppingCartIsEmpty: "你的购物车是空的",
    Delivery: "交付",
    AddProductToCart: "将产品添加到购物车",
    TotalPrice: "总价格:",
    YourDeliveryInfo: "您的送货信息:",
    ShopNow: "商店",
    YourChoice: "你的愿望列表:",
    YourSale: "你的出售:",
    SubtotalPrice: "小计价格:",
    BuyNow: "现在购买",
    Items: "项目",
    Item: "项",
    ThankYou: "谢谢",
    FinishOrderCOD: "您可以使用订单号来跟踪运输状态",
    FinishOrder:
      "非常感谢您的购买,要查看您的送货状态请访问我的订单",
    NextStep: "下一步",
    ConfirmOrder: "确认订单",
    requireenterallfields: "请输入所有字段",
    Error: "错误",
    InvalidEmail: "无效的电子邮件地址",
    Finish: "完成",
    //列表
    NoWishListItem: "没有项目在愿望列表",
    MoveAllToCart: "添加所有到购物车",
    EmptyWishList: "空愿望列表",
    EmptyAddToCart: "抱歉,愿望列表是空的",
    RemoveWishListItemConfirm: "从愿望列表中删除该产品 ?",
    CleanAll: "干净",
    // Sidemenu
    SignIn: "登录",
    SignOut: "注销",
    GuestAccount: "客人账户",
    CantReactEmailError:
      "我们无法到达您的邮箱,请尝试其他登录方式",
    NoEmailError: "您的帐户没有有效的电子邮件地址",
    EmailIsNotVerifiedError:
      "您的电子邮件地址未经验证,我们不能信任您",
    Shop: "商店",
    News: "新闻",
    Contact: "联系我们",
    Setting: "设置",
    Login: "登录",
    Logout: "注销",
    Category: "类别",
    //付款
    Checkout: "结账",
    ProceedPayment: "继续支付",
    Purchase: "购买",
    CashOnDelivery: "货到付款",
    Paypal: "Paypal",
    Stripe: "Stripe",
    CreditCard: "信用卡",
    PaymentMethod: "付款方法 - 不选择",
    PaymentMethodError: "请选择您的支付方式",
    PayWithCoD: "货到付款",
    PayWithPayPal: "您的购买将通过PayPal支付",
    PayWithStripe: "您的购买将被Stripe支付",
    ApplyCoupon: "应用",
    CouponPlaceholder: "优惠券代码",
    APPLY: "应用",
    Back: "回",
    CardNamePlaceholder: "姓名写在卡片上",
    BackToHome: "Back to Home",
    OrderCompleted: "您的订单已完成",
    OrderCanceled: "您的订单被取消",
    OrderFailed: "出了问题……",
    OrderCompletedDesc: "您的订单id是",
    OrderCanceledDesc:
      "你取消了订单。交易尚未完成",
    OrderFailedDesc:
      "我们在处理您的订单时遇到了一个错误。交易尚未完成。请再试一次",
    OrderTip:
      "提示: 你可以在侧边菜单的'我的订单'部分跟踪你的订单状态",
    Payment: "支付",
    Complete: "完成",
    EnterYourFirstName: "输入你的名字",
    EnterYourLastName: "输入你的姓氏",
    EnterYourEmail: "输入你的电子邮件",
    EnterYourPhone: "输入你的手机",
    EnterYourAddress: "输入您的地址",
    CreateOrderError: "无法创建新订单。请稍后再试",
    AccountNumner: "帐号",
    CardHolderName: "持卡人姓名",
    ExpirationDate: "截止日期",
    SecurityCode: "CVV",

    // myorder
    OrderId: "订单ID",
    MyOrder: "我的订单",
    NoOrder: "你没有任何订单",
    OrderDate: "订单日期:",
    OrderStatus: "状态:",
    OrderPayment: "付款方式:",
    OrderTotal: "总:",
    OrderDetails: "细节",
    ShippingAddress: "送货地址:",
    Refund: "退款",
    PostDetails: "细节",
    FeatureArticles: "专题",
    MostViews: "多数意见",
    EditorChoice: "编辑选择",
    //设置
    Settings: "设置",
    BASICSETTINGS: "基本设置",
    Language: "语言",
    INFO: "信息",
    About: "关于我们",
    changeRTL: "开关",
    //语言
    AvailableLanguages: "语言",
    SwitchLanguage: "切换语言",
    SwitchLanguageConfirm: "切换语言需要重新加载应用程序,继续?",
    SwitchRtlConfirm: "Switch RTL需要重新加载应用程序,继续?",
    //关于我们
    AppName: "MSTORE",
    AppDescription: "React Native template for mCommerce",
    AppContact: "联系我们:mstore.io",
    AppEmail: "Email: support@mstore.io",
    appcopyright: "©MSTORE 2016",
    //联系我们
    contactus: "联系我们",
    //表单
    NotSelected: "不选择",
    EmptyError: "此字段为空",
    DeliveryInfo: "传递信息",
    FirstName: "名字",
    LastName: "姓",
    Address: "地址",
    City: "镇/城市",
    State: "状态",
    NotSelectedError: "请选择一个",
    Postcode: "邮政编码",
    Country: "国家",
    Email: "电子邮件",
    Phone: "电话号码",
    Note: "注意",
    //搜索
    Search: "搜索",
    SearchPlaceHolder: "按名称搜索产品",
    NoResultError: "您的搜索关键词与任何产品都不匹配。",
    Details: "细节",
    //过滤板
    Categories: "类别",
    //注册
    profileDetail: "个人资料详情",
    firstName: "名字",
    lastName: "姓",
    accountdetail: "账户信息",
    username: "用户名",
    email: "电子邮件",
    generatpass: "使用生成密码",
    password: "密码",
    signup: "注册",
    //过滤板
    Loading: "加载……",
    welcomeBack: "欢迎回来!",
    seeAll: "显示所有",
    //布局
    cardView: "卡",
    simpleView: "列表视图",
    twoColumnView: "Two Column ",
    threeColumnView: "三列",
    listView: "列表视图",
    default: "默认",
    advanceView: "前进",
    horizontal: "水平",
    couponCodeIsExpired: "此优惠券代码已过期",
    invalidCouponCode: "此优惠券代码无效",
    remove: "删除",
    reload: "重新加载",
    applyCouponSuccess: "恭喜你!优惠券代码申请成功",
    applyCouponFailMin: '此优惠券的最低消费为',
    applyCouponFailMax: '此优惠券的最大消费为',
    OutOfStock: "脱销",
    ShippingType: "运输方式",
    //占位符
    TypeFirstName: "输入你的名字",
    TypeLastName: "输入你的姓",
    TypeAddress: "键入地址",
    TypeCity: "输入你的城镇或城市",
    TypeState: "输入你的状态",
    TypeNotSelectedError: "请选择一个",
    TypePostcode: "邮编",
    TypeEmail: "输入email(例如acb@gmail.com),",
    TypePhone: "输入您的电话号码",
    TypeNote: "注意",
    TypeCountry: "选择",
    SelectPayment: "选择付款方式",
    close: "关闭",
    noConnection: "没有互联网接入",
    //用户配置文件界面
    accountinformation: "账户信息",
    PushNotification: "推送通知",
    DarkTheme: "黑暗主题",
    Privacy: "隐私政策",
    SelectCurrency: "选择货币",
    Name: "名字",
    Currency: "货币",
    Languages: "语言",
    GetDataError: "无法从服务器获取数据",
    UserOrEmail: "用户名或电子邮件",
    Or: "或",
    FacebookLogin: "Facebook登录",
    DontHaveAccount: "没有账户?",
    //水平
    featureProducts: "特色产品",
    bagsCollections: "包集合",
    womanBestSeller: "女性畅销书",
    manCollections: "集合",
    //模态
    Select: "选择",
    Cancel: "取消",
    Guest: "客人",
    LanguageName: "英语",
    //评论
    vendorTitle: "供应商",
    comment: "留下评论",
    yourcomment: "你的评论",
    placeComment:
      "说说你的经历或者给别人留点小费",
    writeReview: "审查",
    thanksForReview:
      "感谢审核,您的内容将由管理员审核,稍后发布",
    errInputComment: "请输入要提交的内容",
    errRatingComment: "请评分提交",
    send: "发送",
    termCondition: "条款与条件",
    Subtotal: "小计",
    Discount: "折扣",
    Shipping: "航运",
    Taxes: "税",
    Recents: "最近",
    Filters: "过滤器",
    Princing: "定价",
    Filter: "过滤器",
    ClearFilter: "清除过滤器",
    ProductCatalog: "产品目录",
    ProductTags: "产品标签",
    AddToAddress: "添加到地址",
    SMSLogin: "短信登录",
    OrderNotes: "订单",

    CanNotLogin: "无法登录，出现问题!",
    PleaseCompleteForm: "请填写表格!",
    ServerNotResponse: "服务器没有正确响应",
    CanNotRegister: "无法注册用户，请重试。",

    UserProfile: "用户资料",
    LoadMore: "加载更多",
    AccountInformations: "用户信息",
  },
  tc:{}
});
